name: 'Build and push chipmunk docs'
description: 'Greet someone and record the time'
inputs:
  src_dir:
    description: 'Repository dir with documentation sources'
    required: true
  dest_dir:
    description: 'Repository dir where results would be pushed'
    required: true
runs:
  using: 'docker'
  image: 'docker://meatlink/chipmunk-docs-gha-builder:debug'
  env:
    CHIPMUNKDOCS_SRC_DIR: ${{ inputs.src_dir }}
    CHIPMUNKDOCS_DEST_DIR: ${{ inputs.dest_dir }}
